Update "Update" file
some bugs with flatpak, flatpak is sucky, don't use it! but i can't...

diff --git a/Import manually/update (add to ⁄usr⁄local⁄bin) b/Import manually/update (add to ⁄usr⁄local⁄bin)
--- a/Import manually/update (add to ⁄usr⁄local⁄bin)
+++ b/Import manually/update (add to ⁄usr⁄local⁄bin)
@@ -3,22 +3,22 @@
 # ----------------------------------
 # Colors
 # ----------------------------------
-NOCOLOR=        '\033[0m'
-RED=            '\033[0;31m'
-GREEN=          '\033[0;32m'
-ORANGE=         '\033[0;33m'
-BLUE=           '\033[0;34m'
-PURPLE=         '\033[0;35m'
-CYAN=           '\033[0;36m'
-LIGHTGRAY=      '\033[0;37m'
-DARKGRAY=       '\033[1;30m'
-LIGHTRED=       '\033[1;31m'
-LIGHTGREEN=     '\033[1;32m'
-YELLOW=         '\033[1;33m'
-LIGHTBLUE=      '\033[1;34m'
-LIGHTPURPLE=    '\033[1;35m'
-LIGHTCYAN=      '\033[1;36m'
-WHITE=          '\033[1;37m'
+NOCOLOR='\033[0m'
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+ORANGE='\033[0;33m'
+BLUE='\033[0;34m'
+PURPLE='\033[0;35m'
+CYAN='\033[0;36m'
+LIGHTGRAY='\033[0;37m'
+DARKGRAY='\033[1;30m'
+LIGHTRED='\033[1;31m'
+LIGHTGREEN='\033[1;32m'
+YELLOW='\033[1;33m'
+LIGHTBLUE='\033[1;34m'
+LIGHTPURPLE='\033[1;35m'
+LIGHTCYAN='\033[1;36m'
+WHITE='\033[1;37m'
 
 # ------------
 # pacman
@@ -47,10 +47,14 @@ fi
 # ------------
 # flatpak
 # ------------
-echo -e ${GREEN}'################### Update system by flatpak... ################'
-    flatpak update -y               || {
-        echo -e ${RED} '############### flatpak command not found, skipping... #################'
-    }
+echo -e ${GREEN}'################### Update system by flatpak...###################'
+	flatpak update --user -y  || {
+        	echo -e ${RED} '############### flatpak command not found, skipping... #################'
+    	}
+    	echo -e ${GREEN} "################### update system-wide app ###################"
+    	flatpak update --system -y       || {
+        	echo -e ${RED} '############### flatpak command not found, skipping... #################'
+    	}
 
 
 clear
@@ -71,9 +75,8 @@ elif command -v paru >/dev/null 2>&1; then
     paru -Scc --noconfirm           || {
         echo -e ${RED} '################# Skipping... ######################'
     }
-elif command -v flatpak >/dev/null 2>&1; then
-    
-    flatpak uninstall --unused -y   || {
+elif command -v flatpak >/dev/null 2>&1; then 
+    flatpak uninstall --user --unused -y   || {
         echo -e ${RED} '################# Skipping... ######################' 
     }
 else
